### ISSUE TITLE
[Controller] SubmissionProblemScore

### ISSUE THREAD

**Issue by emilkovacev** [makeopensource/devU-api#10]
### Feature request
------------------------
Write the controller for SubmissionProblemScore.

## Model
submissionId: foreign_key 
The Submission linked to the SubmissionProblemScore

assignmentProblemId: foreign_key
The assignmentProblem for the submissionProblemScore

score: number
The score for the submissionProblem

feedback: string
Any feedback for the SubmissionProblem

released: date
Date when the SubmissionProblemScore was released

**Comment by zhikangxie107** [comment]
#35
