### ISSUE TITLE
[Service] SubmissionProblemScore

### ISSUE THREAD

**Issue by emilkovacev** [makeopensource/devU-api#11]
### Feature request
------------------------
Implement Service for SubmissionProblemScore. Service provides the core functionality of the app. In this case, it will make database calls (and maybe other calls too?)

## Model
submissionId: foreign_key 
The Submission linked to the SubmissionProblemScore

assignmentProblemId: foreign_key
The assignmentProblem for the submissionProblemScore

score: number
The score for the submissionProblem

feedback: string
Any feedback for the SubmissionProblem

released: date
Date when the SubmissionProblemScore was released

**Comment by Dylanz5** [comment]
Hey Jesse, Please don't look at the previous pull request even though you already merged it. I am a #bot :). Here is hopefully better code.
