### ISSUE TITLE
[Model] Submission Problem Score

### ISSUE THREAD

**Issue by emilkovacev** [makeopensource/devU-api#7]
### Feature request
------------------------
Create the model for the SubmissionProblemScore. The model should follow the pattern specified below.

## Model
submissionId: foreign_key 
The Submission linked to the SubmissionProblemScore

assignmentProblemId: foreign_key
The assignmentProblem for the submissionProblemScore

score: number
The score for the submissionProblem

feedback: string
Any feedback for the SubmissionProblem

released: date
Date when the SubmissionProblemScore was released

**Comment by jessehartloff** [comment]
For the model you'll also need to create the migrations and foreign keys should be renamed to something meaningful. See (https://github.com/UBAutograding/devU-api/pull/28/files#diff-a9ceb6e09dab4ebf26033c8a9a3028286babf23f6c94aa88a6af46c65af4c2fb) for an example migration after changing key names.
